# https://pub.dev/packages/pedantic_mono
include: package:pedantic_mono/analysis_options.yaml

linter:
  rules:
    always_use_package_imports: true # 常に絶対パスでのimportにする
    sort_pub_dependencies: false # pubspec.yamlのdependenciesをソートしない
    
analyzer:
  errors:
    invalid_annotation_target: ignore
  plugins:
    - custom_lint
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
